repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: debug-statements
      - id: trailing-whitespace
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        exclude: |
          (?x)^(
              ^src/
          )
  - repo: https://github.com/PyCQA/pylint
    rev: v2.13.5
    hooks:
      - id: pylint
        exclude: |
          (?x)^(
              ^src/
          )
  - repo: https://github.com/hadolint/hadolint
    rev: v2.8.0
    hooks:
      - id: hadolint
        name: Lint Dockerfiles
        description: Runs hadolint to lint Dockerfiles
        language: system
        types: ["dockerfile"]
        entry: hadolint
